#!/bin/sh
# This script tries to remove imports one by one while making sure that the
# project can still be compiled, so that the minimum number of imports is used.
# This approach is really inefficient, but good enough given that it can just
# be run once in a while to unclutter imports.
# Origin: https://github.com/ChainSecurity/trimport/blob/master/trimport
# Updated Fork: https://github.com/fullkomnun/trimport/blob/master/trimport
set -e
set -u

compile(){
  echo Compiling...
  npx hardhat compile >/dev/null 2>&1
}

echo "This script will run on the following files:"
find 'contracts' -iname '*.sol'
echo "Continue? [y/N]"

read -r answer
if [ "$answer" != "y" ]; then
  exit 2
fi


echo "Compiling once with original files as a sanity check"
compile || exit 3

tmp="$(mktemp)"

find 'contracts' -type f -iname '*.sol' |\
while read -r f ; do
  removed=0
  grep -n '^ *import' "$f" | cut -d':' -f1 |\
    while read -r line; do
      cp "$f" "$tmp"
      line_num=$((line-removed))
      sed -i '' "${line_num}d" "$f"
      removed=$((removed+1))
      if ! compile; then
        echo "reverting"
        cp "$tmp" "$f"
        removed=$((removed-1))
      fi
      
    done
done

exit 0
